print ("Vasiloi Valeria")
print ("13.12.2004")
print ("poșta electronică vavaleria2004@gmail.com")
print ("adresa str. Independenției 10")
print ("studiul curent la IPLT Mihai Eminescu")
print ("studiul primar la Școala Primară Spiridon Vanghelii")
print ("educația preșcolară Gradinița nr. 7")
print ("hobby gaming")
print ("limbi studiate engleza germana chineza")
print ("calitate prietenoasă")
print ("subiect școlar preferat limba engleză")